'use client';
import {useState,useEffect,useRef} from 'react';
import {flushSync} from 'react-dom';
import {ArrowUpRight,ArrowRight,ArrowLeft,Play,Pause,Maximize,Minimize,ChevronRight,ChevronLeft,Check,Plus,Minus,Layers,Compass,FileText,Users,MousePointer2,GripVertical,RotateCcw,Eye,BookOpen,Link2,CheckCircle2,ShieldCheck} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogTrigger} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Slider} from '@/components/ui/slider';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';


type Slide={image:string,title:string,text:string,links:{x:number,y:number,w:number,h:number,url?:string,page?:number}[]};
type Deck={id:string,title:string,subtitle:string,label:string,description:string,count:number,cover:string,pdf:string,slides:Slide[]};
function Picker({value,onChange,options,label}:{value:string,onChange:(v:string)=>void,options:{value:string,label:string}[],label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="picker"><SelectValue/></SelectTrigger><SelectContent position="popper">{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>}
function Kicker({children}:{children:React.ReactNode}){return <div className="kicker">{children}</div>}
export default function DeckViewer({id,children,triggerClassName='portfolio-button',buttonLabel,initialSlide=0,registerPresentationTool=true}:{id:string;children?:React.ReactNode;triggerClassName?:string;buttonLabel?:string;initialSlide?:number;registerPresentationTool?:boolean}){
 const [decks,setDecks]=useState<Deck[]>([]),[catalogError,setCatalogError]=useState(false),[activeDeck,setActiveDeck]=useState<Deck|null>(null),[slide,setSlide]=useState(0),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState('8'),[loop,setLoop]=useState(true),[expanded,setExpanded]=useState(false),[imageError,setImageError]=useState(false),[loadedImage,setLoadedImage]=useState('');
 const [contact,setContact]=useState(false),[copied,setCopied]=useState(false),[reading,setReading]=useState(0);
 const viewerRef=useRef<HTMLDivElement>(null),touchStart=useRef<number|null>(null);
 const reduced=()=>typeof window!=='undefined'&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;
 const fetchCatalog=()=>{setCatalogError(false);fetch('/__GITHUB_PAGES_BASE__/decks/catalog.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{if(!Array.isArray(data))throw Error();setDecks(data as Deck[])}).catch(()=>setCatalogError(true))};
 useEffect(()=>{fetchCatalog()},[]);
 const openDeck=(d:Deck,auto=false)=>{setSlide(0);setActiveDeck(d);setPlaying(auto&&!reduced());setExpanded(false);setImageError(false);setLoadedImage('')};
 const move=(delta:number,manual=true)=>{if(manual)setPlaying(false);setSlide(s=>Math.max(0,Math.min((activeDeck?.count??1)-1,s+delta)))};
 const imageReady=!!activeDeck&&loadedImage===activeDeck.slides[slide]?.image;
 useEffect(()=>{setImageError(false)},[slide,activeDeck?.id]);
 useEffect(()=>{if(!activeDeck||!playing||!imageReady)return;const t=setTimeout(()=>{if(slide>=activeDeck.count-1){if(loop)setSlide(0);else setPlaying(false)}else setSlide(s=>s+1)},Number(speed)*1000);return()=>clearTimeout(t)},[activeDeck,playing,slide,speed,loop,imageReady]);
 useEffect(()=>{if(!activeDeck)return;const i=new Image();i.src=activeDeck.slides[(slide+1)%activeDeck.count].image},[activeDeck,slide]);
 useEffect(()=>{const onHide=()=>{if(document.hidden)setPlaying(false)};document.addEventListener('visibilitychange',onHide);return()=>document.removeEventListener('visibilitychange',onHide)},[]);
 useEffect(()=>{const fs=()=>setExpanded(!!document.fullscreenElement);document.addEventListener('fullscreenchange',fs);return()=>document.removeEventListener('fullscreenchange',fs)},[]);
 useEffect(()=>{const scroll=()=>{const max=document.documentElement.scrollHeight-innerHeight;setReading(max>0?100*scrollY/max:0)};window.addEventListener('scroll',scroll,{passive:true});return()=>window.removeEventListener('scroll',scroll)},[]);
 const fullscreen=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(viewerRef.current?.requestFullscreen)await viewerRef.current.requestFullscreen();else setExpanded(x=>!x)}catch{setExpanded(x=>!x)}};
 const current=activeDeck?.slides[slide];
 useEffect(()=>{
  const context=(document as any).modelContext;if(!registerPresentationTool||!context?.registerTool)return;const lifecycle=new AbortController();
  const register=(tool:any)=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}};
  register({name:'open_'+id.replaceAll('-','_')+'_presentation',description:'Open a portfolio presentation at a specified slide, paused.',inputSchema:{type:'object',properties:{deckId:{type:'string',enum:[id]},slideNumber:{type:'integer',minimum:1}},required:['deckId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:any)=>{const d=decks.find(d=>d.id===id&&d.id===input.deckId);const n=input.slideNumber??1;if(!d||!Number.isInteger(n)||n<1||n>d.count)throw Error('Choose an available deck and slide.');flushSync(()=>{openDeck(d);setSlide(n-1)});return {deck:d.title,slide:n,playing:false}}});
  return()=>lifecycle.abort();
 },[decks,id,registerPresentationTool]);
 const closeDeck=()=>{setPlaying(false);setActiveDeck(null);setExpanded(false);if(document.fullscreenElement)document.exitFullscreen().catch(()=>{})};
 const deck=decks.find(d=>d.id===id);
 return <Dialog open={!!activeDeck} onOpenChange={open=>{if(!open)closeDeck()}}><DialogTrigger asChild><button className={triggerClassName} aria-label={buttonLabel} disabled={!deck} onClick={()=>{if(deck){openDeck(deck);setSlide(Math.max(0,Math.min(deck.count-1,initialSlide)))}}}>{children||<>View full presentation <ArrowUpRight size={17}/></>}</button></DialogTrigger>{catalogError&&<span role="alert" className="viewer-retry">The presentation could not load. <button onClick={fetchCatalog}>Try again</button></span>}
  <DialogContent ref={viewerRef as any} onOpenAutoFocus={e=>{e.preventDefault();viewerRef.current?.focus()}} className={`presentation-dialog ${expanded?'expanded':''}`} onKeyDown={e=>{if((e.target as HTMLElement).closest('input,[role="combobox"],[role="checkbox"],summary'))return;if(e.key==='ArrowRight'){e.preventDefault();move(1)}if(e.key==='ArrowLeft'){e.preventDefault();move(-1)}if(e.key===' '&&e.target===e.currentTarget){e.preventDefault();setPlaying(p=>!p)}}}>
   {activeDeck&&current&&<><div className="viewer-heading"><div><span className="small-label">SELECTED WORK · {activeDeck.label}</span><DialogTitle>{activeDeck.title}</DialogTitle><DialogDescription>{activeDeck.description}</DialogDescription></div></div><div className="slide-stage" onTouchStart={e=>touchStart.current=e.touches[0].clientX} onTouchEnd={e=>{if(touchStart.current!==null){const dx=e.changedTouches[0].clientX-touchStart.current;if(Math.abs(dx)>60)move(dx<0?1:-1);touchStart.current=null}}}>
    {imageError?<div className="slide-error"><p>This slide image could not load.</p><button className="btn outline" onClick={()=>setImageError(false)}>Retry slide</button></div>:<><button className="slide-click" aria-label={slide===activeDeck.count-1?'Last slide. Restart presentation.':'Next slide'} onClick={()=>{setPlaying(false);setSlide(s=>s===activeDeck.count-1?0:s+1)}}><img key={current.image} src={current.image} alt={`${activeDeck.title}, slide ${slide+1}: ${current.title}. Full text is available below.`} onLoad={()=>setLoadedImage(current.image)} onError={()=>{setImageError(true);setPlaying(false)}}/></button>{current.links.filter(l=>!l.url||(/^https?:\/\//i.test(l.url)&&!/\.(pdf|zip|pptx?|docx?|xlsx?|json)(?:$|[?#])/i.test(l.url))).map((l,i)=>l.url?<a className="slide-hotspot" key={i} style={{left:`${l.x*100}%`,top:`${l.y*100}%`,width:`${l.w*100}%`,height:`${l.h*100}%`}} href={l.url} target="_blank" rel="noopener noreferrer" aria-label={`Open source link ${i+1}: ${l.url}`} onClick={()=>setPlaying(false)}/>:<button className="slide-hotspot" key={i} style={{left:`${l.x*100}%`,top:`${l.y*100}%`,width:`${l.w*100}%`,height:`${l.h*100}%`}} aria-label={`Go to slide ${(l.page??0)+1}`} onClick={()=>{setPlaying(false);setSlide(l.page??0)}}/>)}</>}
   </div><Progress value={(slide+1)/activeDeck.count*100} className="slide-progress" aria-label="Presentation progress"/><div className="player-controls"><div className="playback"><button className="icon-btn" aria-label="Previous slide" disabled={slide===0} onClick={()=>move(-1)}><ChevronLeft/></button><button className="btn play-btn" disabled={imageError} onClick={()=>{if(slide===activeDeck.count-1&&!loop)setSlide(0);setPlaying(p=>!p)}}>{playing?<Pause size={16}/>:<Play size={16}/>} {playing?'Pause':'Play'}</button><button className="icon-btn" aria-label="Next slide" disabled={slide===activeDeck.count-1} onClick={()=>move(1)}><ChevronRight/></button><span className="page-status" role="status" aria-live={playing?'off':'polite'}>{String(slide+1).padStart(2,'0')} <span>/ {activeDeck.count}</span></span></div><div className="play-options"><Picker value={speed} onChange={setSpeed} label="Autoplay speed" options={[{value:'5',label:'5 sec'},{value:'8',label:'8 sec'},{value:'12',label:'12 sec'},{value:'20',label:'20 sec'}]}/><label className="checkbox-label"><Checkbox checked={loop} onCheckedChange={v=>setLoop(v===true)}/>Loop</label><button className="icon-btn" onClick={fullscreen} aria-label={expanded?'Exit fullscreen':'Fullscreen presentation'}>{expanded?<Minimize size={18}/>:<Maximize size={18}/>}</button></div></div>
   <p className="slide-navigation-hint">Click the slide, swipe or use the arrows to continue.</p><div className="slide-thumbs" aria-label="Choose a slide">{activeDeck.slides.map((s,i)=><button key={s.image} aria-label={`Slide ${i+1}: ${s.title}`} aria-current={slide===i?'true':undefined} className={slide===i?'selected':''} onClick={()=>{setPlaying(false);setSlide(i)}}><img src={s.image} alt="" loading="lazy"/><span>{i+1}</span></button>)}</div><details className="slide-transcript"><summary>Slide text & viewing tips <ChevronRight size={14}/></summary><p>Click a slide, swipe, or use the left and right arrow keys. Play advances automatically at your chosen speed. Manual navigation pauses playback.</p><pre>{current.text||'This slide uses image-based text. Use fullscreen for a larger view.'}</pre></details><p className="viewer-disclosure">{activeDeck.label}. No endorsement or award is implied.</p></>}
  </DialogContent></Dialog>;
}
