'use client';

import {useState} from 'react';
import {Check,ClipboardCheck,RotateCcw,ScanLine,ShieldCheck} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import w from '@/content/workshop.json';

type Review='idle'|'pending'|'approved'|'declined'|'expired';
type PlanSnapshot={id:string;line:string;quantity:number;ready:number;version:number};
const lines=[
 {id:'boots',name:'Field boots',detail:'Size 10 Regular · Sample revision B',quantity:120,stock:72,unit:'pairs',target:10,first:8,second:9,wrong:'Size 9 Regular'},
 {id:'uniforms',name:'Uniform sets',detail:'Medium Regular · Sample revision C',quantity:500,stock:320,unit:'sets',target:15,first:12,second:14,wrong:'Large Regular'},
 {id:'gear',name:'Textile tactical packs',detail:'30 L configuration · Sample revision A',quantity:200,stock:140,unit:'packs',target:12,first:10,second:11,wrong:'Different pack configuration'}
];

export default function ManufacturingPrototype({scenario,onScenarioChange,architecture}:{scenario:string;onScenarioChange:(s:string)=>void;architecture:string}){
 const [lineId,setLineId]=useState('boots'),[choice,setChoice]=useState('primary'),[verified,setVerified]=useState(false),[review,setReview]=useState<Review>('idle'),[snapshot,setSnapshot]=useState<PlanSnapshot|null>(null),[resolved,setResolved]=useState<'recorded'|'escalated'|null>(null);
 const line=lines.find(l=>l.id===lineId)!;
 const test=w.testCases.find(t=>t.id===scenario)||w.testCases[0];
 const gap=line.quantity-line.stock;
 const plans=[
  {id:'primary',name:'Released stock + primary production slot',ready:scenario==='late'?line.target+4:line.first,reason:`Use ${line.stock} released ${line.unit}; produce ${gap} more in the confirmed primary slot.`,issue:'',available:scenario!=='mismatch'},
  {id:'alternate',name:'Released stock + alternate production slot',ready:scenario==='late'?line.target+6:line.second,reason:`Use the same ${line.stock} released ${line.unit}; produce the remaining ${gap} in a later confirmed slot.`,issue:'',available:scenario!=='mismatch'},
  {id:'wrong',name:'Similar stock with a requirement mismatch',ready:2,reason:line.wrong+' does not meet this order line.',issue:'Wrong size or configuration',available:true},
  {id:'hold',name:'Lot awaiting quality release',ready:3,reason:'The quantity exists, but the lot remains on a quality hold.',issue:'Quality hold unresolved',available:true}
 ];
 const eligible=(p:typeof plans[number])=>p.available&&!p.issue&&p.ready<=line.target;
 const selected=plans.find(p=>p.id===choice)!;
 const hasPlan=plans.some(eligible);
 const approved=review==='approved'&&verified&&eligible(selected)&&snapshot?.id===selected.id&&snapshot.line===lineId&&snapshot.quantity===line.quantity&&snapshot.ready===selected.ready;
 const resetReview=()=>{setVerified(false);setReview('idle');setSnapshot(null);setResolved(null)};
 const selectPlan=(id:string)=>{setChoice(id);resetReview()};
 const requestReview=()=>{if(!verified||!eligible(selected)||review!=='idle'||resolved)return;setSnapshot({id:selected.id,line:lineId,quantity:line.quantity,ready:selected.ready,version:1});setReview('pending')};
 const decide=(value:Review)=>{if(review==='pending'&&snapshot)setReview(value)};
 const status=resolved==='recorded'?'Approved recovery plan recorded in the demo.':resolved==='escalated'?'Exception assigned to the operations lead in the demo.':review==='approved'?'Operations approved this exact plan. Ready to record.':review==='declined'?'Plan rejected. Keep the order on hold for replanning.':review==='expired'?'Review deadline missed. Keep the plan on hold.':review==='pending'?'Waiting for an operations decision. No commitment recorded.':!hasPlan?'No eligible recovery plan. An owned exception is needed.':'No recovery plan approved yet.';
 return <div className="nil-prototype manufacturing-prototype">
  <div className="nil-prototype-toolbar"><div><span className="small-label">INTERACTIVE SIMULATION</span><p>{architecture==='team'?'Demand → Production → Evidence → Human review':'One planning agent + quality and operations review'}</p></div><div className="nil-pickers"><Select value={lineId} onValueChange={v=>{setLineId(v);setChoice('primary');resetReview()}}><SelectTrigger aria-label="Manufacturing product"><SelectValue/></SelectTrigger><SelectContent>{lines.map(l=><SelectItem key={l.id} value={l.id}>{l.name}</SelectItem>)}</SelectContent></Select><Select value={scenario} onValueChange={onScenarioChange}><SelectTrigger aria-label="Prototype scenario"><SelectValue/></SelectTrigger><SelectContent>{w.testCases.map(t=><SelectItem key={t.id} value={t.id}>{t.name}</SelectItem>)}</SelectContent></Select></div></div>
  <p className="nil-scenario"><strong>{test.name}:</strong> {test.signal}</p>
  <div className="nil-order"><span className="nil-status-label">SAMPLE ORDER · SIZE-LEVEL SUPPLY GAP</span><h4>{line.name}</h4><p>{line.detail} · Ship-by target: Day {line.target}</p><div className="manufacturing-order-metrics"><div><strong>{line.quantity}</strong><span>{line.unit} required</span></div><div><strong>{line.stock}</strong><span>{line.unit} released</span></div><div><strong>{gap}</strong><span>{line.unit} to produce</span></div></div><p className="nil-demo-notice">Day numbers are relative to the start of this fictional planning exercise. These are sample product requirements, not military specifications.</p></div>
  <div className="nil-demo-grid">
   <section className="nil-shopper" aria-label="Manufacturing recovery plan selection"><span className="nil-step-label">01 / PRODUCTION PLANNER</span><h4>Compare feasible recovery plans.</h4><p>Keep the exact item, size and revision. Check released stock, materials, production capacity and inspection timing.</p><RadioGroup value={choice} onValueChange={selectPlan} aria-label="Recovery plan" className="nil-product-list">{plans.filter(p=>p.available).map(p=><label key={p.id} className={`nil-product ${choice===p.id&&eligible(p)?'nil-selected':''} ${!eligible(p)?'nil-ineligible':''}`}><RadioGroupItem value={p.id} disabled={!eligible(p)||!!resolved||review==='expired'||review==='declined'} aria-label={p.name}/><span><strong>{p.name}</strong><span className="nil-product-price">{p.issue?'Not eligible':`Planned completion: Day ${p.ready}`}</span><span className="nil-product-reason">{p.reason}</span><span className="nil-product-fit">{p.issue||p.ready>line.target?`Blocked: ${p.issue||'completion is after the ship-by target'}`:p.id==='primary'?'Suggested plan · earliest eligible completion':'Eligible alternative · later completion'}</span></span></label>)}</RadioGroup>
    {hasPlan?<><div className="nil-verification"><ScanLine size={19}/><p>{verified?'Demo evidence confirmed: exact item and revision, released lot, material availability, production slot and inspection timing.':scenario==='stale'?'Records are one day old. Refresh inventory, allocations, capacity and quality status before requesting review.':'Sample records are current. The planner and quality reviewer still need to verify the evidence for this plan.'}</p></div><button className="btn outline" disabled={verified||!!resolved||review!=='idle'} onClick={()=>setVerified(true)}>{verified?<Check size={17}/>:<ScanLine size={17}/>} {verified?'Evidence verified in demo':'Simulate record refresh & verification'}</button></>:<p className="nil-empty">No option meets all requirements. Preserve the hold and assign an exception. Do not change the size, clear a quality hold or silently move the target date.</p>}
   </section>
   <section className="nil-customer" aria-label="Operations plan review"><span className="nil-step-label">02 / OPERATIONS REVIEWER</span><h4>Review the plan before committing.</h4><p>Inspect the exact quantity, completion date and supporting evidence. Quality staff retain final product-release authority.</p>
    <div className="nil-message"><div className="nil-message-heading"><ClipboardCheck size={18}/><strong>Northstar · planning review</strong></div>{hasPlan?<><p><strong>{selected.name}</strong></p><dl><dt>Requirement</dt><dd>{line.quantity} {line.unit} · {line.detail}</dd><dt>Recovery</dt><dd>{line.stock} released + {gap} planned</dd><dt>Completion / target</dt><dd>Day {selected.ready} / Day {line.target}</dd><dt>Evidence</dt><dd>{verified?'Inventory, materials, capacity and quality checked':'Verification pending'}</dd><dt>Plan record</dt><dd>{line.id.toUpperCase()} / {selected.id.toUpperCase()} · Version 1</dd></dl><p>Approval covers this planning record. Any changed lot, requirement, quantity, date or quality status must return for review.</p><span className="nil-message-state">{review==='idle'?'DRAFT · NOT REQUESTED':review==='pending'?'DEMO REVIEW REQUESTED':review==='approved'?'OPERATIONS APPROVED IN DEMO':review==='declined'?'PLAN REJECTED IN DEMO':'REVIEW WINDOW EXPIRED IN DEMO'}</span></>:<><p>The current options cannot fulfill the unchanged requirement by Day {line.target}. Assign the operations lead to confirm the next production option and coordinate a revised commitment if needed.</p><span className="nil-message-state">EXCEPTION · NO PLAN APPROVED</span></>}</div>
    {hasPlan&&<button className="btn primary" onClick={requestReview} disabled={!verified||review!=='idle'||!!resolved}><ClipboardCheck size={17}/>Simulate requesting plan review</button>}
    {review==='pending'&&<div className="nil-response"><strong>Try the reviewer’s decision</strong><div className="button-row">{scenario!=='declined'&&scenario!=='no-reply'&&<button className="btn primary" onClick={()=>decide('approved')}>Reviewer approves plan</button>}{scenario!=='no-reply'&&<button className="btn outline" onClick={()=>decide('declined')}>Reviewer rejects plan</button>}<button className="text-link" onClick={()=>decide('expired')}>Simulate missed review deadline</button></div><p>The review window advances only when you choose a decision or the deadline.</p></div>}
    <p className="nil-demo-notice">Fictional data and decisions. No company, Army or production system is connected. No request is sent or order changed.</p>
   </section>
  </div>
  <section className="nil-checkout" aria-label="Plan approval gate"><div><span className="nil-step-label">03 / RECORD THE DECISION</span><h4 role="status">{status}</h4><p>{resolved==='escalated'?'Owner: operations lead. Next action: replan with production and quality, then coordinate the delivery exception.':approved?`The reviewed plan covers ${line.quantity} ${line.unit}, with completion on Day ${selected.ready}. Final quality release and shipping remain separate steps.`:'The agent assembles evidence. People approve the plan and own the next action.'}</p></div><div className="nil-checkout-actions"><button className="btn primary" disabled={!approved||!!resolved} onClick={()=>{if(approved)setResolved('recorded')}}><ShieldCheck size={17}/>Record approved plan</button>{(!hasPlan||review==='declined'||review==='expired')&&<button className="btn outline" disabled={!!resolved} onClick={()=>setResolved('escalated')}>Assign exception to operations</button>}<button className="text-link" onClick={()=>{setChoice('primary');resetReview()}}><RotateCcw size={15}/>Reset this scenario</button></div></section>
  <details className="detail"><summary>What the agent checks <ShieldCheck size={17}/></summary><ol><li>Match the ordered item, size, revision and quantity.</li><li>Separate released inventory from allocated and quality-held lots.</li><li>Verify material, production and inspection capacity against the target date.</li><li>Keep source timestamps and the exact reviewed plan together.</li><li>Hold changed, rejected or unanswered plans for human action.</li></ol><p><strong>Before a live pilot:</strong> validate these proposed checks against the manufacturer’s actual processes, order terms and decision authorities.</p></details>
 </div>;
}
