import {Header,Footer} from './chrome';
import {ContactButton,ResumeButton} from './popouts';
import LaunchCover from './launch/cover';
import {ArrowUpRight,Presentation,ChartNoAxesCombined,PanelsTopLeft,MessagesSquare,Layers3,Plus,Database,Lightbulb,Users,Target,Workflow,BriefcaseBusiness,Network} from 'lucide-react';
export const metadata={title:'Meghan Fasano | Federal Proposals, Orals & Executive Storytelling',description:'Meghan Fasano supports federal proposals, proposal orals and FEDSIM pursuits through narrative strategy, presentation design and presenter preparation, alongside executive storytelling, UX and human-centered AI.'};
const certifications=[
 {name:'AI Transformation Leader',exam:'AB-731',badge:'/__GITHUB_PAGES_BASE__/images/certifications/ab-731.svg',href:'https://learn.microsoft.com/en-us/credentials/certifications/ai-transformation-leader/'},
 {name:'Azure AI Engineer Associate',exam:'AI-102',badge:'/__GITHUB_PAGES_BASE__/images/certifications/ai-102.svg',href:'https://learn.microsoft.com/en-us/credentials/certifications/azure-ai-engineer/'},
 {name:'Azure AI Fundamentals',exam:'AI-900',badge:'/__GITHUB_PAGES_BASE__/images/certifications/ai-900.svg',href:'https://learn.microsoft.com/en-us/credentials/certifications/azure-ai-fundamentals/'}
];
const capabilities=[
 {image:'/__GITHUB_PAGES_BASE__/decks/core-ai/001.webp',imageAlt:'CoreAI executive presentation cover',icon:Presentation,number:'01',name:'Executive storytelling',headline:'Make the message matter.',body:'I turn strategy, technical detail and competing inputs into a focused story for leaders, customers and teams.',deliverables:'Executive decks · Keynotes · Leadership briefings · Customer narratives',href:'/__GITHUB_PAGES_BASE__/work/core-ai',link:'Explore presentation design'},
 {image:'/__GITHUB_PAGES_BASE__/decks/axis-nova/004-v2.webp',imageAlt:'Axis Nova proposal concept visual',icon:MessagesSquare,number:'02',name:'Federal proposals & orals',headline:'Make the value unmistakable.',body:'I support federal pursuit teams with proposal narratives, storyboards and oral presentations that connect the customer’s priorities to the solution and help presenters tell one clear story.',deliverables:'Federal proposals · Proposal orals · Storyboards · Presenter preparation',href:'/__GITHUB_PAGES_BASE__/work/axis-nova',link:'Explore federal proposal orals'},
 {image:'/__GITHUB_PAGES_BASE__/decks/meridian-arc/001-v3.png',imageAlt:'Meridian Arc FEDSIM-style orals presentation cover',icon:ChartNoAxesCombined,number:'03',name:'FEDSIM orals & data stories',headline:'Make complexity clear.',body:'I translate systems, data and technical concepts into visuals that explain what matters, why it matters and what to do next.',deliverables:'Power BI dashboards · Concept visuals · Solution diagrams · Data stories',href:'/__GITHUB_PAGES_BASE__/work/meridian-arc',link:'Explore FEDSIM information design'},
 {image:'',imageAlt:'',icon:PanelsTopLeft,number:'04',name:'UX & human-centered AI',headline:'Make the experience useful.',body:'I bridge business and technical teams through UX/UI design, Jobs to Be Done discovery and workshops that shape practical AI agents.',deliverables:'UX/UI · Prototypes · Design systems · Agent-design workshops',href:'/__GITHUB_PAGES_BASE__/work/microsoft-launch-tool',link:'Explore UX leadership'}
];
const roles=[['2025–Present','The Peerless Group','Tech Innovator / AI Futurist','Executive presentations, AI proposal assets and customer discovery workshops.'],['2023–2025','Microsoft','Lead UX Designer','UX/UI, interactive prototypes and a reusable design system for an internal launch tool.'],['2019–2023','Microsoft','Senior Marketing Communications Manager','Executive decks, customer narratives and technical demos for Worldwide Retail & Consumer Goods.'],['2007–2019','P3Solutions · Microsoft assignment','Sales Communications & Proposal Strategist','Led proposal and oral-presentation design supporting $12B+ in contract wins. Coordinated 60+ proposals annually, including major federal pursuits, reviews and presenter preparation. Experience includes FEDSIM orals and JEDI pursuit support.']];
const toolGroups=[
 {title:'Story & design',icon:Presentation,tools:['PowerPoint','Adobe Creative Cloud','Figma'],detail:'Executive storytelling · Information design · UX/UI'},
 {title:'Data & insight',icon:ChartNoAxesCombined,tools:['Microsoft Fabric','Power BI','Copilot in Fabric & Power BI'],detail:'Data visualization · Dashboard design · Decision-focused narratives'},
 {title:'AI & automation',icon:Lightbulb,tools:['Azure AI','Copilot Studio','Power Platform','Power Apps','Power Automate','Microsoft 365 Copilot','Copilot in Power Apps & Power Automate'],detail:'Agent design · Workflow automation · Human-centered AI'},
 {title:'Cloud & development',icon:Layers3,tools:['Microsoft Azure','Azure DevOps','GitHub','GitHub Copilot','Visual Studio','VS Code'],detail:'Prototyping · Developer collaboration · Design through delivery'}
];
export default function About(){return <div className="folio" id="top"><Header active="about"/><main id="main" className="folio-wrap about-executive">
 <section className="ae-hero" aria-labelledby="about-title"><div className="ae-hero-copy"><p className="folio-eyebrow">MEGHAN FASANO / COMMUNICATIONS & DESIGN LEADER</p><h1 id="about-title">Your vision.<br/>A story that<br/><em>moves people.</em></h1><p className="ae-intro">I’m Meghan. I turn complex business and technology ideas into clear narratives, compelling presentations and experiences people can use.</p><p className="ae-hero-note">From federal proposals and FEDSIM orals to executive decks, I connect the message, the visuals and the people who need to act.</p><div className="ae-hero-actions"><ContactButton className="portfolio-button" intent="consultation">Let’s plan your story <ArrowUpRight size={18}/></ContactButton><ResumeButton className="ae-text-link">View my résumé ↗</ResumeButton></div><a className="ae-text-link ae-federal-jump" href="#federal-title">Federal proposals, proposal orals & FEDSIM work</a><span className="ae-location">Charleston, South Carolina</span></div><figure className="ae-portrait"><a className="ae-hero-skill ae-skill-story" href="#support-title"><Presentation size={24}/><span>Executive<br/><strong>storytelling</strong></span><ArrowUpRight size={14}/></a><a className="ae-hero-skill ae-skill-data" href="#human-title"><ChartNoAxesCombined size={24}/><span>Data made<br/><strong>meaningful</strong></span><ArrowUpRight size={14}/></a><a className="ae-hero-skill ae-skill-ai" href="#tools-title"><Network size={24}/><span>Human-centered<br/><strong>AI & design</strong></span><ArrowUpRight size={14}/></a><div className="ae-portrait-space"><img className="ae-portrait-photo" src="/__GITHUB_PAGES_BASE__/images/meghan-portrait.png" alt="Meghan Fasano in her office" width={1638} height={2048} loading="eager"/></div><figcaption><strong>Meghan Fasano</strong><span>Executive storyteller. Design leader.<br/>Translator between business and technology.</span></figcaption></figure></section>
 <section className="ae-proof-strip" aria-label="Experience at a glance"><div><span className="ae-proof-icon"><BriefcaseBusiness size={28}/></span><strong>18<span> years</span></strong><p>Approximately, across Microsoft employee and vendor roles.</p></div><div><span className="ae-proof-icon"><Target size={28}/></span><strong>$12B<span>+</span></strong><p>Contract wins supported through proposal and storytelling work.</p></div><div className="ae-proof-words"><span className="ae-proof-icon"><Network size={28}/></span><strong>Strategy.<br/> Design. Technology.</strong><p>A connected perspective, from the business question to the experience.</p></div></section>
 <section className="ae-section ae-federal" aria-labelledby="federal-title">
  <div className="ae-section-heading"><div><p className="folio-eyebrow">FEDERAL PROPOSAL SUPPORT</p><h2 id="federal-title">Proposal orals.<br/><em>FEDSIM experience.</em></h2></div><p>I help pursuit teams turn complex technical and management inputs into a clear proposal story. My experience includes federal proposals, FEDSIM orals and JEDI pursuit support.</p></div>
  <div className="ae-federal-experience"><p>At P3Solutions on a Microsoft vendor assignment, I coordinated 60+ proposals annually, including major federal pursuits, reviews and presenter preparation.</p><ul aria-label="Federal proposal capabilities"><li>Narrative strategy & storyboards</li><li>Proposal graphics & orals decks</li><li>Review support & presenter preparation</li></ul></div>

 </section>
 <section className="ae-section" aria-labelledby="support-title"><div className="ae-section-heading"><div><p className="folio-eyebrow">WHAT I CAN OWN FOR YOU</p><h2 id="support-title">The story. The system.<br/><em>The details that matter.</em></h2></div><p>When the stakes are high and the material is complex, I bring structure, visual clarity and a consistent story across the work.</p></div><div className="ae-capabilities">{capabilities.map(({icon:Icon,...c})=><article key={c.number}><div className="ae-cap-visual">{c.image?<a href={c.href} aria-label={c.link}><img src={c.image} alt={c.imageAlt} loading="lazy"/></a>:<LaunchCover/>}</div><div className="ae-cap-content"><div className="ae-cap-top"><span className="ae-cap-icon"><Icon size={30} strokeWidth={1.65}/></span><span>{c.number} / {c.name}</span></div><h3>{c.headline}</h3><p>{c.body}</p><div className="ae-deliverables">{c.deliverables}</div><a href={c.href}>{c.link}<ArrowUpRight size={17}/></a></div></article>)}</div></section>
 <section className="ae-section ae-leadership" aria-labelledby="leadership-title"><div className="ae-section-heading"><div><p className="folio-eyebrow">HOW I LEAD</p><h2 id="leadership-title">I see the big picture.<br/><em>And build the story.</em></h2></div><p>I bring a designer’s craft, a storyteller’s judgment and a leader’s ability to connect people. My role is to help business, technical and creative teams communicate with one clear purpose.</p></div><div className="ae-leadership-grid">{[
 ['Start with the decision.','Who is the audience? What do they need to understand, believe or do? I use those answers to shape the narrative before the slides.'],
 ['Bring the right people together.','I connect leaders, subject-matter experts, designers and developers, translating different perspectives into a coherent experience.'],
 ['Carry the work through.','I stay connected from story and structure to visual design, review and delivery. On the Microsoft launch tool, I led UX with two junior teammates and partnered with developers using Azure DevOps.']
 ].map(([title,body],i)=><article key={title}><div className="ae-lead-step"><span className="ae-lead-icon">{i===0?<Target size={29}/>:i===1?<Users size={29}/>:<Workflow size={29}/>}</span><span>0{i+1}</span></div><h3>{title}</h3><p>{body}</p></article>)}</div></section>

 <section className="ae-section ae-human" aria-labelledby="human-title"><div className="ae-human-copy"><p className="folio-eyebrow">HUMANIZING TECHNOLOGY</p><h2 id="human-title">Better stories.<br/>More useful data.<br/><em>AI with a purpose.</em></h2><p>I bridge the business and technical gap by starting with people and the work they need to get done. In design thinking workshops, I use Jobs to Be Done to uncover that need, align the team and shape agents that help people finish real work.</p><a className="ae-text-link" href="https://www.christenseninstitute.org/theory/jobs-to-be-done/" target="_blank" rel="noopener noreferrer">Jobs to Be Done · Christensen Institute ↗</a><a className="ae-text-link" href="/__GITHUB_PAGES_BASE__/work/agent-workshop">Explore the workshop case study ↗</a></div><div className="ae-data-story"><span className="folio-eyebrow">FROM DATA TO A DECISION</span><h3>Give the insight<br/><em>a clear story.</em></h3><ol><li><span className="ae-flow-icon"><Database size={22}/></span><div><strong>Microsoft Fabric</strong><p>Connect and shape the data around the business question.</p></div></li><li><span className="ae-flow-icon"><ChartNoAxesCombined size={22}/></span><div><strong>Power BI</strong><p>Make the pattern, comparison or change easy to see.</p></div></li><li><span className="ae-flow-icon"><MessagesSquare size={22}/></span><div><strong>Executive storytelling</strong><p>Explain why it matters and what decision comes next.</p></div></li></ol></div></section>
 <section className="ae-section ae-tool-section" aria-labelledby="tools-title"><div className="ae-section-heading"><div><p className="folio-eyebrow">TOOLS & DISCIPLINES</p><h2 id="tools-title">A connected toolkit.<br/><em>A clear business purpose.</em></h2></div><p>Presentation craft comes first. Data, AI and development tools help me carry the story into the dashboards, workflows and experiences people use.</p></div><div className="ae-tools">{toolGroups.map(({title,icon:Icon,tools,detail})=><article key={title}><div><Icon size={21}/><h3>{title}</h3></div><ul>{tools.map(tool=><li key={tool}>{tool}</li>)}</ul><p>{detail}</p></article>)}</div><section className="ae-certifications" aria-labelledby="certifications-title"><h3 id="certifications-title">MICROSOFT CERTIFICATIONS</h3><div className="ae-certification-grid">{certifications.map(cert=><a className="ae-certification-card" key={cert.exam} href={cert.href} target="_blank" rel="noopener noreferrer" aria-label={cert.name+' certification details (opens in a new tab)'}><img src={cert.badge} alt={'Microsoft Certified: '+cert.name+' badge'} width={88} height={88} loading="lazy"/><span className="ae-certification-copy"><strong>{cert.name}</strong><span className="ae-certification-exam">{cert.exam}</span><span className="ae-certification-link">Certification details <ArrowUpRight size={15}/></span></span></a>)}</div></section></section>
 <section className="ae-career"><details><summary><span>Experience at a glance</span><Plus size={20}/></summary><div>{roles.map(([date,company,title,body])=><article key={title}><span>{date}</span><div><h3>{company}</h3><strong>{title}</strong><p>{body}</p></div></article>)}</div></details></section>
 </main><Footer/></div>}
