'use client';

import {useState, type ReactNode} from 'react';
import {Dialog, DialogContent, DialogTitle, DialogDescription, DialogTrigger} from '@/components/ui/dialog';
import {ArrowUpRight, Copy, Check, Maximize2} from 'lucide-react';

export function ImagePreview({src,alt,loading='lazy',showPreviewBadge=true}:{src:string;alt:string;loading?:'eager'|'lazy';showPreviewBadge?:boolean}){
  return <Dialog><DialogTrigger asChild><button className="image-preview-trigger" aria-label={'Enlarge image: '+alt}><img src={src} alt={alt} loading={loading}/>{showPreviewBadge&&<span className="preview-badge"><Maximize2 size={15}/> Enlarge</span>}</button></DialogTrigger><DialogContent className="portfolio-popout image-popout"><DialogTitle>{alt}</DialogTitle><DialogDescription>Full image preview</DialogDescription><img className="popout-image" src={src} alt={alt}/></DialogContent></Dialog>
}

export function ContactButton({children='Contact',className='',label,intent='general'}:{children?:ReactNode;className?:string;label?:string;intent?:'general'|'consultation'|'hiring'}){
  const [copied,setCopied]=useState(false),[copyError,setCopyError]=useState(false);
  const copy={general:{title:'Let’s connect.',description:'Executive storytelling, visual communications and human-centered AI.',action:'Write an email',subject:'',body:''},consultation:{title:'Let’s plan your project.',description:'Tell me about your goals and share a few times that work for you. We’ll discuss scope, priorities and how I can help.',action:'Email meeting request',subject:'Planning meeting with Meghan Fasano',body:'Hi Meghan,\n\nI’d like to set up a planning conversation.\n\nMy project or challenge:\nWhat I’d like to achieve:\nIdeal timeline:\nA few times I’m available (with time zone):\n\nThank you!'},hiring:{title:'Let’s work together.',description:'Ready to get started? Share the role or project, what success looks like and your ideal timeline.',action:'Email hiring inquiry',subject:'Hiring inquiry for Meghan Fasano',body:'Hi Meghan,\n\nI’d like to discuss working together.\n\nThe role or project:\nWhat success looks like:\nIdeal timeline:\nNext steps:\n\nThank you!'}}[intent];
  const emailHref='mailto:meghan@choosepeerless.com'+(copy.subject?'?subject='+encodeURIComponent(copy.subject)+'&body='+encodeURIComponent(copy.body):'');
  return <Dialog onOpenChange={()=>{setCopied(false);setCopyError(false)}}><DialogTrigger asChild><button className={className} aria-label={label}>{children}</button></DialogTrigger><DialogContent className="portfolio-popout contact-popout"><DialogTitle>{copy.title}</DialogTitle><DialogDescription>{copy.description}</DialogDescription><p className="contact-person">Meghan Fasano<span>Charleston, South Carolina</span></p><a className="contact-email" href={emailHref}>meghan@choosepeerless.com</a><div className="popout-actions"><a className="portfolio-button" href={emailHref}>{copy.action} <ArrowUpRight size={16}/></a><button className="copy-email" onClick={async()=>{try{await navigator.clipboard.writeText('meghan@choosepeerless.com');setCopied(true);setCopyError(false)}catch{setCopyError(true)}}}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'Email copied':'Copy email address'}</button></div><p className="copy-status" role="status">{copyError?'Please select and copy the email address above.':copied?'Email address copied to your clipboard.':''}</p><a className="contact-linkedin" href="https://www.linkedin.com/in/meghanfasano1/" target="_blank" rel="noopener noreferrer" aria-label="View Meghan Fasano’s LinkedIn profile (opens in a new tab)">View LinkedIn profile <ArrowUpRight size={17}/></a></DialogContent></Dialog>
}

const resumeRoles=[
  ['Jun 2025–Present','The Peerless Group','Tech Innovator / AI Futurist','Create executive presentations and AI-enabled proposal assets. Facilitate discovery workshops and turn stakeholder input into customer journeys and recommendations.'],
  ['Apr 2023–Jul 2025','Global technology company','Lead UX Designer','Led UX/UI, information architecture and interactive prototypes for an internal launch tool. Built a reusable Figma component and style library with cross-functional partners.'],
  ['Aug 2019–Mar 2023','Global technology company | Worldwide Retail & Consumer Goods','Senior Marketing Communications Manager','Designed executive decks, technical demos and customer narratives. Aligned sales, architects, specialists and customer leaders around solution value and next steps.'],
  ['Jul 2007–Aug 2019','P3Solutions | global technology company assignment','Sales Communications & Proposal Strategist','Led proposal and orals design supporting $12B+ in contract wins. Coordinated 60+ proposals annually, including major federal pursuits, reviews and presenter preparation.']
];
export function ResumeButton({className='',children='Résumé'}:{className?:string;children?:ReactNode}){return <Dialog><DialogTrigger asChild><button className={className}>{children}</button></DialogTrigger><DialogContent className="portfolio-popout resume-popout"><DialogTitle>Meghan Fasano · Résumé</DialogTitle><DialogDescription>Visual design & executive communications · Charleston, SC</DialogDescription><div className="resume-content"><p>Communications and design leader who turns complex technology into clear executive narratives, compelling presentations and human-centered experiences. Approximately 18 years across employee and vendor roles at a global technology company, with proposal and storytelling work supporting $12B+ in contract wins.</p><section><h3>Selected work & impact</h3><ul><li><strong>Executive storytelling:</strong> Materials for senior commercial leadership and support for the a CEO-to-CEO engagement with FedEx.</li><li><strong>Customer discovery:</strong> A 2.5-day Sam’s Club executive workshop using Design Thinking and Jobs to Be Done; AI demonstration narratives for Walmart.</li><li><strong>Federal proposals & orals:</strong> Federal proposal support, FEDSIM orals and JEDI pursuit support, including proposal narratives, presentation design, reviews and presenter preparation.</li><li><strong>Strategic communications:</strong> Solution framing and executive narratives for Walgreens Boots Alliance.</li></ul></section><section><h3>Professional experience</h3>{resumeRoles.map(([date,company,title,body])=><article className="resume-role" key={title}><span>{date}</span><h4>{company}</h4><p className="resume-role-title">{title}</p><p>{body}</p></article>)}<p>Earlier: COE, Production Manager / IT Administrator (May 2005–Mar 2007). Federal proposal production, document control and on-time submission.</p></section><section><h3>Capabilities & credentials</h3><p><strong>Design & strategy:</strong> Presentation design, Adobe Creative Cloud, Figma, executive storytelling, information design, UX/UI, Design Thinking and Jobs to Be Done.</p><p><strong>AI credentials:</strong> Certified in AI transformation leadership, AI engineering and AI fundamentals. Details available on request.</p><p><strong>Education:</strong> Marymount University, BA, Liberal Arts and Sciences; The George Washington University School of Business, UX/UI Design.</p></section><a className="portfolio-button" href="mailto:meghan@choosepeerless.com">Contact Meghan <ArrowUpRight size={16}/></a></div></DialogContent></Dialog>}
