import {Header,Footer} from './chrome';
import {ImagePreview} from './popouts';
import w from '@/content/workshop.json';

const phases=[
  {title:'Start with the soldier. Align the factory.',photo:'manufacturing-discover',body:'I connect the person who needs correctly fitting gear with the teams who plan, manufacture and release it. Together, we define the progress each person needs to make.',output:'Two Jobs to Be Done, an evidence wall and a shared definition of success.',links:[['Open the sticky notes',1],['Explore the job stories',2]]},
  {title:'Turn a shortage into a clear decision.',photo:'manufacturing-design',body:'I map demand, inventory, materials, production and quality. The agent concept brings those records into a recovery plan that a person can inspect and approve.',output:'An agent blueprint with traceable inputs, clear responsibilities and human review.',links:[['See the workflow',3],['Compare agent designs',4],['Try the planning prototype',5]]},
  {title:'Test the plan before making a promise.',photo:'manufacturing-test',body:'I challenge the plan with wrong sizes, held lots, stale records and missed dates. Then I define a pilot and the data story: from Fabric to Power BI, showing delivery reliability, exceptions and planning effort.',output:'Six test scenarios, an owned decision log and a measurable pilot plan.',links:[['Explore the test cases',6],['See the pilot decision',7]]}
];
export default function WorkshopStory(){return <div className="folio" id="top"><Header/><main id="main" className="folio-wrap">
  <section className="case-intro workshop-case-intro"><a className="back-link" href="/__GITHUB_PAGES_BASE__/">← Back to home</a><p className="folio-eyebrow">NORTHSTAR OUTFITTERS / MANUFACTURING & AI</p><h1>Right gear.<br/><em>Ready on time.</em></h1><p className="case-lede">A fictional manufacturer supplies U.S. Army soldiers with uniforms, boots and tactical gear. This workshop turns a size-specific shortage into a clear, human-approved production plan.</p><div className="case-quicklinks"><a className="portfolio-button" href="/__GITHUB_PAGES_BASE__/workshop/explore#chapter-1">Explore the sticky notes ↗</a><a href="/__GITHUB_PAGES_BASE__/workshop/explore#chapter-5">Try the planning prototype ↗</a></div></section>
  <section className="case-summary" aria-label="Case study at a glance"><div><h2>The problem</h2><p>120 pairs of boots required. Only 72 released in the correct size. Production and quality teams need a dependable plan for the remaining 48.</p></div><div><h2>My contribution</h2><p>JTBD framing, cross-team facilitation, agent experience design, interactive prototyping and data storytelling.</p></div><div><h2>The output</h2><p>A planning assistant concept that connects demand, inventory, capacity and quality evidence for a human decision.</p></div></section>
  <section className="workshop-phases" aria-label="My approach">{phases.map((phase,i)=><article className="workshop-step" key={phase.photo}><figure><ImagePreview src={'/__GITHUB_PAGES_BASE__/images/agent-workshop/'+phase.photo+'.webp'} alt={'Illustrative manufacturing workshop scene: '+phase.title}/></figure><div><span className="folio-eyebrow">0{i+1} / MY APPROACH</span><h2>{phase.title}</h2><p>{phase.body}</p><div className="step-output"><span>THE OUTPUT</span><p>{phase.output}</p></div><div className="phase-links">{phase.links.map(([label,step])=><a className="activity-link" key={String(step)} href={'/__GITHUB_PAGES_BASE__/workshop/explore#chapter-'+step}>{label} ↗</a>)}</div></div></article>)}</section>
  <p className="folio-disclosure">{w.disclosure}</p><p className="workshop-reference-links">{w.sources.map(source=><a key={source.url} href={source.url} target="_blank" rel="noopener noreferrer">{source.title} ↗</a>)}</p><a className="next-project" href="/__GITHUB_PAGES_BASE__/work/core-ai"><span>Next case study</span><strong>CoreAI ↗</strong></a>
</main><Footer/></div>}
