import {Header,Footer} from '../../chrome';
import LaunchExperience from '../../launch/experience';
import {ArrowUpRight,Users,Workflow,CheckCircle2} from 'lucide-react';

export const metadata={title:'Product Launch Tool | UX/UI Leadership | Meghan Fasano',description:'Meghan Fasano’s UX leadership on an internal business-planning launch tool, with a reconstructed before-and-after experience and an interactive dashboard concept.'};
const decisions=[
 ['Start with the next decision.','A planner needs to see what is blocked, who owns it and what happens next. Readiness, approvals and risks share the first view.'],
 ['Make consumption understandable.','Keep each meter’s quantity, unit, region and pricing assumption together. A usage forecast is distinct from estimated cost and recognized revenue.'],
 ['Bring the outside view inside.','Market briefs, customer feedback and reviews sit beside the launch plan, with their source and relevance visible.'],
 ['Connect design to delivery.','Work items include acceptance criteria, review states and release dependencies so the design can be discussed with developers and tested.']
];
export default function LaunchCase(){return <div className="folio launch-case" id="top"><Header/><main id="main">
 <div className="folio-wrap"><section className="case-intro launch-case-intro"><a className="back-link" href="/__GITHUB_PAGES_BASE__/">← Back to home</a><p className="folio-eyebrow">PRODUCT LAUNCH TOOL / UX & UI LEADERSHIP</p><h1>Bringing product launches<br/><em>into focus.</em></h1><p className="case-lede">Helping business planners connect the business case, cloud consumption and delivery decisions in one clear experience.</p><div className="launch-role-strip"><div><span>MY ROLE</span><strong>UX lead</strong></div><div><span>DESIGN TEAM</span><strong>Me + 2 junior UX teammates</strong></div><div><span>DELIVERY PARTNERSHIP</span><strong>Developers · Sprint & release planning</strong></div></div><p className="launch-provenance">Based on my work on an internal product launch tool. The screens below are portfolio reconstructions with fictional products and sample data, not screenshots of the internal tool or claims about its measured results.</p><div className="case-quicklinks"><a className="portfolio-button" href="#launch-experience">Explore the before & after <ArrowUpRight size={18}/></a><a href="#launch-leadership">See my role and approach ↗</a></div></section></div>
 <section className="launch-experience-section" id="launch-experience" aria-labelledby="experience-heading"><div className="folio-wrap"><div className="launch-section-heading"><div><p className="folio-eyebrow">01 / THE EXPERIENCE</p><h2 id="experience-heading">From scattered details<br/>to <em>decision clarity.</em></h2></div><p>Compare a reconstructed fragmented workflow with an interactive dashboard concept. Open the approvals, meters, feedback and delivery views.</p></div><LaunchExperience/></div></section>
 <div className="folio-wrap"><section className="launch-narrative" id="launch-leadership"><div className="launch-section-heading"><div><p className="folio-eyebrow">02 / MY LEADERSHIP</p><h2>Design leadership.<br/><em>Shared delivery.</em></h2></div><p>I was the UX lead, working with two junior UX team members and the development team. We tracked sprints and deployments together.</p></div><div className="launch-team"><article><Users size={23}/><span>UX LEAD</span><h3>Meghan Fasano</h3><p>UX leadership for the business-planning launch experience.</p></article><article><Workflow size={23}/><span>DESIGN COLLABORATION</span><h3>Two junior UX teammates</h3><p>A small UX team working together on the product.</p></article><article><CheckCircle2 size={23}/><span>ENGINEERING PARTNERSHIP</span><h3>Connected through delivery</h3><p>Collaboration with developers, with sprint and deployment tracking throughout delivery.</p></article></div></section>
 <section className="launch-narrative"><div className="launch-section-heading"><div><p className="folio-eyebrow">03 / THE DESIGN RATIONALE</p><h2>Every view answers<br/><em>a planner’s question.</em></h2></div><p>The reconstruction centers on a proposed planner job: “When a launch is approaching, help me understand readiness, resolve open decisions and make a credible launch commitment.”</p></div><div className="launch-decision-grid">{decisions.map(([title,body],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{body}</p></article>)}</div><div className="launch-journey" aria-label="Proposed planner journey">{[['Frame','Audience, value and investment'],['Plan','Milestones, meters and owners'],['Review','Evidence, decisions and conditions'],['Deliver','Sprint, QA and release status'],['Learn','Consumption and customer signals']].map(([title,body],i)=><div key={title}><span>0{i+1}</span><strong>{title}</strong><p>{body}</p></div>)}</div></section>
 <section className="launch-narrative"><div className="launch-section-heading"><div><p className="folio-eyebrow">04 / FROM DESIGN TO DEVELOPMENT</p><h2>Make the handoff<br/><em>part of the design.</em></h2></div><p>The proposed delivery model makes design intent reviewable: a user need becomes a work item, acceptance criteria, a testable state and a release decision.</p></div><div className="launch-handoff"><div><h3>One component. Every state.</h3><p>The approval panel demonstrates pending, approved and changes-requested states. It keeps the plan version, reviewer and evidence together. The same visual language carries through status labels, tables and dialogs.</p><div className="launch-state-samples"><span>Awaiting review</span><span>Approved</span><span>Changes requested</span></div></div><div><h3>A reviewable sprint artifact.</h3><p>In the Delivery view, open a sample work item to inspect its owner, sprint and acceptance criteria. Business-plan approval remains separate from a production deployment approval.</p><a href="#launch-experience">Explore the dashboard ↗</a></div></div></section>
 <section className="launch-narrative launch-evidence"><div className="launch-section-heading"><div><p className="folio-eyebrow">05 / VALIDATION & OUTCOMES</p><h2>Prove the experience<br/><em>with the work.</em></h2></div><p>These are proposed validation tasks and measures for the reconstruction. Historical usability findings and performance metrics have not been supplied, so no improvement percentages are claimed.</p></div><div className="launch-test-list">{[
 ['Find the next decision','Ask a planner to locate the highest-priority blocker and its owner.','Measure time, wrong turns and whether the next action is understood.'],
 ['Explain the forecast','Ask a planner to explain the meter unit, actual usage and forecast assumptions.','Check comprehension without help; confirm units are never mixed.'],
 ['Review the business case','Ask a reviewer to approve a plan or request changes with a reason.','Observe completion, evidence use, decision clarity and recovery from errors.'],
 ['Use it with a keyboard','Complete navigation, meter inspection and approval without a mouse.','Check focus order, focus return, visible states and access to chart data.']
 ].map(([task,method,measure],i)=><article key={task}><span>0{i+1}</span><div><h3>{task}</h3><p>{method}</p></div><p>{measure}</p></article>)}</div><details className="launch-reference-detail"><summary>Reconstruction notes</summary><p>These portfolio screens use fictional products, sample data and proposed workflows to demonstrate the design approach. They are not screenshots of an internal product or claims about measured results.</p></details></section><a className="next-project" href="/__GITHUB_PAGES_BASE__/work/connected-ai"><span>Next case study</span><strong>Connected AI ↗</strong></a></div>
 </main><Footer/></div>}
